config/routes.rb
Rails.application.routes.draw do

  resources :companies

  devise_for :users
  resources :messages
  resources :products

  get 'contact/form'

root 'home#index'

get 'home/index'
get 'home/terms'
get 'home/privacy'

get 'labels/index'
get 'monitoring/index'
get 'server_access/index'
get 'shipment/index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products
  has_many :users

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/message.rb
class Message < ActiveRecord::Base

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :company


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :js



  def show
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)

  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
    current_user.company_id = @company.id
    current_user.save
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = current_user.company


    end

    def company_params
      params.require(:company).permit(:name, :type, :registration_number, :vat_number, :age, :size, :address, :zip_code, :city, :country, :phone_number, :website, :logo)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:fullname, :email, :country, :phone_number, :company, :object, :content)
    end
end

app/controllers/monitoring_controller.rb
class MonitoringController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

respond_to :html, :xml, :js

  def index
    @products = current_user.company.products
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new

    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_user.company_id
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = current_user.company.products.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:picture, :name, :category, :subcategory, :alone_volume, :batch_volume, :amount_per_batch, :alone_mass, :batch_mass, :reference)
    end
end

app/controllers/shipment_controller.rb
class ShipmentController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def active_for(path)
    "active" if current_page?(path)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/monitoring_helper.rb
module MonitoringHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/server_access_helper.rb
module ServerAccessHelper
end

app/helpers/shipment_helper.rb
module ShipmentHelper
end

app/views/companies/_form.html.slim
= form_for(@company) do |f|
  - if @company.errors.any?
    #error_explanation
      h2
        = pluralize(@company.errors.count, "error")
        |  prohibited this company from being saved:
      ul
        - @company.errors.full_messages.each do |message|
          li
            = message
  .row
    .small-6.columns
      .field
        = f.file_field :logo

        = f.label :name
        br
        = f.text_field :name
      .field
        = f.label :company_type
        br
        = f.text_field :company_type
      .field
        = f.label :registration_number
        br
        = f.number_field :registration_number
      .field
        = f.label :vat_number
        br
        = f.text_field :vat_number
      .field
        = f.label :age
        br
        = f.text_field :age
      .field
        = f.label :size
        br
        = f.text_field :size
      .field
        = f.label :address
        br
        = f.text_field :address
      .field
        = f.label :zip_code
        br
        = f.text_field :zip_code
      .field
        = f.label :city
        br
        = f.text_field :city
      .field
        = f.label :country
        br
        = f.text_field :country
      .field
        = f.label :phone_number
        br
        = f.text_field :phone_number
      .field
        = f.label :website
        br
        = f.text_field :website
      .actions
        = f.submit

app/views/companies/edit.html.slim
h1
  | Editing company
= render 'form'

.row
  .small-6.colums
    = link_to 'Show', @company, class: "button success"

app/views/companies/new.html.slim
h1
  | New company
= render 'form'

p |

app/views/companies/show.html.slim
.row
    p#notice
      = notice


    = image_tag @company.logo.url(:medium)

    p
      strong
        | Id:
      = @company.id

    p
      strong
        | Name:
      = @company.name
    p
      strong
        | Company type:
      = @company.company_type
    p
      strong
        | Registration number:
      = @company.registration_number
    p
      strong
        | Vat number:
      = @company.vat_number
    p
      strong
        | Age:
      = @company.age
    p
      strong
        | Size:
      = @company.size
    p
      strong
        | Address:
      = @company.address
    p
      strong
        | Zip code:
      = @company.zip_code
    p
      strong
        | City:
      = @company.city
    p
      strong
        | Country:
      = @company.country
    p
      strong
        | Phone number:
      = @company.phone_number
    p
      strong
        | Website:
      = @company.website
    = link_to 'Edit', edit_company_path(@company), class: "button success"

app/views/messages/_form.html.slim
= form_for(@message) do |f|
  - if @message.errors.any?
    #error_explanation
      h2
        = pluralize(@message.errors.count, "error")
        |  prohibited this message from being saved:
      ul
        - @message.errors.full_messages.each do |message|
          li
            = message
  .row
    .large-6.columns
      = f.label :fullname
      = f.text_field :fullname

    .large-6.columns
      = f.label :email
      = f.text_field :email

  .row
    .large-4.columns
      = f.label :country
      = f.text_field :country

    .large-4.columns
      = f.label :phone_number
      = f.text_field :phone_number

    .large-4.columns
      = f.label :company
      = f.text_field :company

  .row
    .large-12.columns
      = f.label :object
      = f.text_field :object

  .row
    .large-12.columns
      = f.label :content
      = f.text_field :content

  .row
    .actions
      .large-12.columns
       = f.button :submit
        | Envoyer

app/views/messages/edit.html.slim
.row
  .columns.large-12
    h1
      | Nous contacter

= render 'form'

.row
  .columns.large-2
    = link_to 'Show', @message,  class:"left button default"

  .columns.large-10
    = link_to 'Back', messages_path, class:"left button default"

app/views/messages/index.html.slim
h1
  | Listing messages
table
  thead
    tr
      th
        | Fullname
      th
        | Email
      th
        | Country
      th
        | Phone number
      th
        | Company
      th
        | Object
      th
        | Content
      th[colspan="3"]
  tbody
    - @messages.each do |message|
      tr
        td
          = message.fullname
        td
          = message.email
        td
          = message.country
        td
          = message.phone_number
        td
          = message.company
        td
          = message.object
        td
          = message.content
        td
          = link_to 'Show', message
        td
          = link_to 'Edit', edit_message_path(message)
        td
          = link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Message', new_message_path

app/views/messages/new.html.slim
h1
  | Contactez-nous
= render 'form'

.row
  .columns.large-2
    = link_to 'Back', messages_path, class: "button default"

app/views/messages/show.html.slim
p#notice
  = notice
p
  strong
    | Fullname:
  = @message.fullname
p
  strong
    | Email:
  = @message.email
p
  strong
    | Country:
  = @message.country
p
  strong
    | Phone number:
  = @message.phone_number
p
  strong
    | Company:
  = @message.company
p
  strong
    | Object:
  = @message.object
p
  strong
    | Content:
  = @message.content
= link_to 'Edit', edit_message_path(@message)
|  | 
= link_to 'Back', messages_path

app/views/products/_form.html.slim
= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      h2
        = pluralize(@product.errors.count, "error")
        |  prohibited this product from being saved:
      ul
        - @product.errors.full_messages.each do |message|
          li
            = message
  .row
    .columns.small-12
      .row.collapse
        = f.file_field :picture


      .row.collapse
        = f.label :name
        = f.text_field :name

      .row.collapse
        = f.label :category
        = f.text_field :category

      .row.collapse
        = f.label :subcategory
        = f.text_field :subcategory

      .row.collapse
        = f.label :alone_volume
        = f.text_field :alone_volume

      .row.collapse
        = f.label :batch_volume
        = f.text_field :batch_volume

      .row.collapse
        = f.label :amount_per_batch
        = f.number_field :amount_per_batch

      .row.collapse
        = f.label :alone_mass
        = f.text_field :alone_mass

      .row.collapse
        = f.label :batch_mass
        = f.text_field :batch_mass

      .row.collapse
        = f.label :reference
        = f.text_field :reference

      .row.collapse
        .actions
        = f.submit

app/views/products/edit.html.slim
h1
  | Editing product
= render 'form'
= link_to 'Show', @product
|  | 
= link_to 'Back', products_path

app/views/products/index.html.slim
= render 'layouts/sub_nav'

h1
  | Listing products
table
  thead
    tr
      th
        | Picture
      th
        | Name
      th
        | Category
      th
        | Subcategory
      th
        | Alone volume
      th
        | Batch volume
      th
        | Amount per batch
      th
        | Alone mass
      th
        | Batch mass
      th
        | Reference

      th
        | Company_id

      th[colspan="3"]
  tbody
    - @products.each do |product|
      tr
        td
          = image_tag product.picture.url
        td
          = product.name
        td
          = product.category
        td
          = product.subcategory
        td
          = product.alone_volume
        td
          = product.batch_volume
        td
          = product.amount_per_batch
        td
          = product.alone_mass
        td
          = product.batch_mass
        td
          = product.reference
        td
          = product.company_id

        td
          = link_to 'Show', product
        td
          = link_to 'Edit', edit_product_path(product)
        td
          = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Product', new_product_path, class: "button success"

app/views/products/new.html.slim
.row
  .columns.small-12
    h1
      | New product
    = render 'form'

    = link_to 'Back', products_path, class: "button success"

app/views/products/show.html.slim
.row
    p#notice
      = notice


    = image_tag @product.picture.url(:medium)


    p
      strong
        | Name:
      = @product.name

    p
      strong
        | Category:
      = @product.category

    p
      strong
        | Subcategory:
      = @product.subcategory
    p
      strong
        | Alone volume:
      = @product.alone_volume

    p
      strong
        | Batch volume:
      = @product.batch_volume
    p
      strong
        | Amount per batch:
      = @product.amount_per_batch

    p
      strong
        | Alone mass:
      = @product.alone_mass

    p
      strong
        | Batch mass:
      = @product.batch_mass

    p
      strong
        | Reference:
      = @product.reference

    = link_to 'Edit', edit_product_path(@product), class: "button success"
    |
    = link_to 'Back', products_path, class: "button success"