config/routes.rb
Rails.application.routes.draw do

  resources :companies

  devise_for :users
  resources :messages
  resources :products

  get 'contact/form'

root 'home#index'

get 'home/index'
get 'home/terms'
get 'home/privacy'

get 'labels/index'
get 'monitoring/index'
get 'server_access/index'
get 'shipment/index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products
  has_many :users

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/message.rb
class Message < ActiveRecord::Base

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :company


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :js



  def show
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)

  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
    current_user.company_id = @company.id
    current_user.save
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = current_user.company


    end

    def company_params
      params.require(:company).permit(:name, :type, :registration_number, :vat_number, :age, :size, :address, :zip_code, :city, :country, :phone_number, :website, :logo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:fullname, :email, :country, :phone_number, :company, :object, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

respond_to :html, :xml, :js

  def index
    @products = current_user.company.products
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new

    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_user.company_id
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = current_user.company.products.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:picture, :name, :category, :subcategory, :alone_volume, :batch_volume, :amount_per_batch, :alone_mass, :batch_mass, :reference)
    end
end

app/controllers/shipment_controller.rb
class ShipmentController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def active_for(path)
    "active" if current_page?(path)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/monitoring_helper.rb
module MonitoringHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/server_access_helper.rb
module ServerAccessHelper
end

app/helpers/shipment_helper.rb
module ShipmentHelper
end

app/views/layouts/_footer.html.slim
#footer
  .row
    .column.small-12.text-center
      =link_to "Terms",  home_terms_path
      | |
      =link_to "Privacy",  home_privacy_path

app/views/layouts/_sub_nav.html.slim
dl.sub-nav

  dd class=active_for(products_path)
    a[href= products_path ]
      | 1 - Catalogue
  dd class=active_for(labels_index_path)
    a[href=labels_index_path]
      | 2 - Etiquettes
  dd class=active_for(shipment_index_path)
    a[href=shipment_index_path]
      | 3 - Transport
  dd class=active_for(monitoring_index_path)
    a[href=monitoring_index_path]
      | 4 - Suivi

  dd class=active_for(server_access_index_path)
    a[href=server_access_index_path]
      | 5 - Accès au serveur de gestion de logistique

app/views/layouts/_top_bar.html.slim
nav.top-bar[data-topbar role="navigation" data-options="is_hover: false"]
  ul.title-area
    li.name
      h1
        a[href="/"]
          | Cap logistique
    li.toggle-topbar.menu-icon
      a[href="#"]
        span
          | Menu
  section.top-bar-section
    ul.right

      - if user_signed_in?
          -if current_user.company_id?

            li
              a[href=products_path]
                | Dashboard
          -else
            li
              = link_to "Ajouter mon compte entreprise", new_company_path

          li
            = link_to current_user.email




          li.has-dropdown
            a[href="#"]
              | Mon compte
            ul.dropdown
              li
                = link_to "Paramètres du compte utilisateur", edit_user_registration_path

              -if current_user.company_id?

                li
                  = link_to "Consulter mon compte entreprise", company_path(current_user.company_id)

              -else

                li
                  = link_to "Ajouter mon compte entreprise", new_company_path

              li
                = link_to "Se déconnecter", destroy_user_session_path, method: :delete
      -else

        li
          a[href="/"]
            | Solution d'externalisation de logistique
        li
          a[href=new_message_path]
            | Nous contacter

        li.has-dropdown
          a[href="#"]
            | Espace Membre
          ul.dropdown
            li
              a[href=new_user_session_path]
                | Accéder à son compte Cap
            li
              a[href=new_user_registration_path]
                | Nouveau compte

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Cap Performance - Solutions de logistique externalisée"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag



    = render 'layouts/top_bar'

    

    body

    == yield

    = javascript_include_tag "application"


    = render 'layouts/footer'